[package]
name = "id_generator"
version = "0.1.0"
authors = ["Max Leonard Inden <IndenML@gmail.com>"]
edition = "2018"

[dependencies]
queues = "1.0.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
